### ISSUE TITLE
Zynonym trojan/virus in Version 2.9.5?

### ISSUE THREAD

**Issue by WB0OCV** [jopohl/urh#1094] opened 2023-12-27 12:16 UTC
I just downloaded the 64-bit version 2.9.5 (28-Oct-2023), and upon installation, Windows Defender quarantines the urh_debug.exe executable as containing the Zynonym trojan/virus. I tried downloading the 32-bit version of v2.9.5, and Google blocks the download entirely as being a dangerous file. I downloaded and installed the 64-bit version of v2.9.4 (28-Jan-2023), and it installs without any problem or identification of a virus. Can the author of URH v2.9.5 please check the program for potential incorporation of a Trojan/virus and recompile if necessary? Thank you.

**Comment by WB0OCV** [comment] 2023-12-27 12:17
I just downloaded the 64-bit version 2.9.5 (28-Oct-2023), and upon installation, Windows Defender quarantines the urh_debug.exe executable as containing the Zynonym trojan/virus. I tried downloading the 32-bit version of v2.9.5, and Google blocks the download entirely as being a dangerous file. I downloaded and installed the 64-bit version of v2.9.4 (28-Jan-2023), and it installs without any problem or identification of a virus. Can the author of URH v2.9.5 please check the program for potential incorporation of a Trojan/virus and recomile if necessary? Thank you.

**Comment by jopohl** [comment] 2023-12-27 17:09
Looks like a duplicate of https://github.com/jopohl/urh/issues/1075

**Comment by jopohl** [comment] 2024-01-14 00:07
The false-positives are caused by PyInstaller - see [here](https://github.com/pyinstaller/pyinstaller/issues?q=label%3Aantivirus-false-positives+) for a list of issues.

Just released URH v2.9.6 with a more recent Python version (3.11) and built with PyInstaller 6.3.0.

Please contact your anti-virus vendor if the new version gets still quarantined. There is not much URH can do about such false-positives.

**Closed by jopohl** 2024-01-14 00:07 UTC
