### ISSUE TITLE
Does not recognize Windows Install of GNURadio. 

### ISSUE THREAD

**Issue by chibill** [jopohl/urh#145] opened 2017-02-22 04:23 UTC
No matter what I do I can't get it to see my GNURadio install. (Which was installed with GNURadio's Windows installer)

**Comment by jopohl** [comment] 2017-02-22 14:23
Thanks for bringing this up @chibill .
I made a nearly working fix in https://github.com/jopohl/urh/pull/147.

However, Gnuradio itself seems to be kind of bugged on Windows. The Gnuradio Backend is based on TCP sockets like this:
![grc](https://cloud.githubusercontent.com/assets/18219846/23215367/646ca98c-f912-11e6-8fcc-5be3176d7539.png)

However, if I try to connect via python to this socket with:
```python
import socket
socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.connect(("127.0.0.1", 1337))
```
Gnuradio just exits completly. On Linux this works like a charm.

Any ideas on this?

**Comment by chibill** [comment] 2017-02-22 14:30
No idea. So the gnuradio back end is basiclly a rtl_tcp backend. Can you at least make it so we can just start rtl_tcp and use that?

Also you could directly use the librtlsdr that already has a ctypes wrapper for it.

**Comment by chibill** [comment] 2017-02-22 14:33
I can try what you posted on my end and see if anything happens.

**Comment by jopohl** [comment] 2017-02-22 15:04
Let me know, if you find out anything.

**Comment by chibill** [comment] 2017-02-22 15:19
Also I does not like where I point it to my python 2.7.13 install.

Also the TCP Sink is deprecated so that could cause  a problem later on.

No idea why it hangs it but. Makes python go none responsive.

Anyway for me to make urh connect to rtl_tcp server instead?

**Comment by jopohl** [comment] 2017-02-22 15:41
In perspective we will move away from Gnuradio backend. First, the TCP sink is deprecated as you mentioned and second, the UDP sink also does not work. Hang on, we are currently working on enhancing the native device support.

For ``` rtl_tcp``` you could have a look at ``` urh/plugins/NetworkSDRInterface/NetworkSDRInterfacePlugin.py ``` and implement a  ``` SDRPlugin ```. This is intended for this kind of stuff.

**Comment by chibill** [comment] 2017-02-22 17:24
There is also using librtlsdr directly. (Or using pyrtlsdr a ctypes wrapped around it)

**Comment by jopohl** [comment] 2017-02-22 17:49
Yes, creating a librtlsdr wrapper with Cython has high priority for me currently.

**Comment by chibill** [comment] 2017-02-22 18:06
You could look at the pure python ctypes wrapper for help with that maybe?

**Comment by jopohl** [comment] 2017-02-22 18:11
Yes that will be my starting point. :wink:

**Comment by andynoack** [comment] 2017-02-23 09:15
Gnuradio has a confirmed bug on Windows in respect to the TCP sink we are using for the SDR-backend: https://github.com/gnieboer/GNURadio_Windows_Build_Scripts/issues/15
We are working on a solution! Stay tuned.

**Comment by jopohl** [comment] 2017-02-25 14:25
Fixed with https://github.com/jopohl/urh/pull/147

**Closed by jopohl** 2017-02-25 14:25 UTC
Labels: installation
