### ISSUE TITLE
Two issues on Linux

### ISSUE THREAD

**Issue by bluegizmo83** [jopohl/urh#554] opened 2018-10-20 03:28 UTC
Hi, I'm back again lol :)

I just installed URH on my Linux system (Parrot OS), and I have two issues with it so far. I installed it via sudo pip3 install urh, and then also tried updating via pip3 install --upgrade urh.

1. I'm on version 2.4.0 but I don't see the DC Correction option in the live recording options (it does show up as a filter option after recording though!)
2. I can't use the Spectrum Analyzer on the Linux install for some reason. As soon as I hit start, URH immediately closes completely. Record Signal still works fine though.

**Comment by jopohl** [comment] 2018-10-20 07:32
Welcome back :smile: 

I think both of your issues are caused by the same problem:
1. The DC Correction is only available for devices with __native backend__ enabled
2. Switching to native backend will most likely also fix the crash

So just go to Edit -> Options -> Device and switch to native backend for your SDR.

**Comment by jopohl** [comment] 2018-10-21 10:37
You are missing the airspy.h file. Assuming that you are using ubuntu, did you install the ``` libairspy-dev ``` package?

**Comment by jopohl** [comment] 2018-10-24 08:22
I am closing here due to missing response. Just drop a comment if you want this issue reopened.

**Closed by jopohl** 2018-10-24 08:22 UTC
